# Use the official Node.js image as the base image
FROM node:20-alpine as builder

ENV NODE_ENV build

USER node
WORKDIR /home/node

COPY package*.json ./
RUN npm ci

COPY --chown=node:node . .
RUN  npm run build \
    && npm prune --omit=dev

# Use the official Nginx image as the base image
FROM nginx

# Copy the static files generated by Next.js into the Nginx container
COPY --from=builder /home/node/build /usr/share/nginx/html

# Expose port 80 to allow external access
EXPOSE 80

# Command to start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]
